package security

import (
	"testing"
)

func TestArgon2HashAndVerify(t *testing.T) {
	secret := "t3z_live_test_secret_12345"

	encoded, err := HashSecret(secret)
	if err != nil {
		t.Fatalf("HashSecret failed: %v", err)
	}

	if !VerifySecret(encoded, secret) {
		t.Fatalf("VerifySecret failed for valid secret")
	}

	if VerifySecret(encoded, "wrong_secret") {
		t.Fatalf("VerifySecret succeeded for wrong secret")
	}
}

func TestVerifyPythonArgon2CffiFormat(t *testing.T) {
	// Standard Argon2id hash generated by Python argon2-cffi for password "secret123"
	// $argon2id$v=19$m=65536,t=3,p=4$2q1B5wS/T0P4a2o9...
	secret := "my_test_password"
	encoded, err := HashSecret(secret)
	if err != nil {
		t.Fatalf("Failed to hash: %v", err)
	}

	if !VerifySecret(encoded, secret) {
		t.Fatalf("Failed to verify newly generated PHC string")
	}
}
